name: Build and Release
on:
  release:
    types: [published, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install build tool
        run: npm -g add mc-build@3.6.7
      - name: Build project
        run: mcb build
      - name: Package
        run: zip -r riscvmc.zip data/ LICENSE pack.mcmeta
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./riscvmc.zip
          asset_name: riscvmc-v${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
